name = "backend-nuevo"
main = "worker.js"
compatibility_date = "2024-12-01"

[vars]
SUPABASE_URL = "https://brsxoocptqwjmdqcavig.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc3hvb2NwdHF3am1kcWNhdmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMTQyNTAsImV4cCI6MjA4MDc5MDI1MH0.QIQAC6Fi1qV3Ho8w3Ie1wDQZdVSKLPZniRtdSApKrWY"
